Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np

arr = np.arange(2, 50, 3)
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [ ]:
#creating empty lists
list_1 = []
list_2 = []


#creating variable for taking input from user for list_1 and arr_1
print("Enter 5 element for the list_1: ")
for i in range(5):
    elements = int(input())
    list_1.append(elements)
print("list_1=", list_1)
arr_1 = np.array(list_1)
print("\n arr_1=", arr_1)

#creating variable for taking input from user for list_2 and arr_2
print("\nEnter 5 element for the list_2: ")
for i in range(5):
    elements = int(input())
    list_2.append(elements)
print("list_2=", list_2)
arr_2 = np.array(list_2)
print("\n arr_2=", arr_2)

#concatenating arrays
arr_3 = np.concatenate((arr_1, arr_2))
print("\n Concatenated array:", arr_3)

#sortng the array
arr_4 = np.sort(arr_3)
print("\n Sorted array:", arr_4)




Enter 5 element for the list_1: 
89
96
45
12
3
list_1= [89, 96, 45, 12, 3]

 arr_1= [89 96 45 12  3]

Enter 5 element for the list_2: 
78
56
36
20
1
list_2= [78, 56, 36, 20, 1]

 arr_2= [78 56 36 20  1]

 Concatenated array: [89 96 45 12  3 78 56 36 20  1]

 Sorted array: [ 1  3 12 20 36 45 56 78 89 96]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [ ]:
#creating an array
arr = np.array([[1,2,3,4], [9,8,7,6]])
print("Array:", arr)

#basic characteristics of array
print("\nClass of Array:", type(arr))

print("\nSize of Array:", arr.size)

print("\nDimension of array:", arr.ndim)

Array: [[1 2 3 4]
 [9 8 7 6]]

Class of Array: <class 'numpy.ndarray'>

Size of Array: 8

Dimension of array: 2


Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [13]:
import numpy as np


a = np.array([1, 2, 3, 4, 5, 6])
print(a, a.shape)
print("\n Dimension of array:", a.ndim)

#Demonterating np.newaxis
a2 = a[np.newaxis, :]
print("\n", a2, a2.shape)
print("\n Dimension of array:", a2.ndim)


#We can convert a 1D array with either a row vector or a column vector using np.newaxis. 
row_vector = a[np.newaxis, :]
print("\n", row_vector, row_vector.shape)
print("\n Dimension of array:", row_vector.ndim)


col_vector = a[:, np.newaxis]
print("\n", col_vector, col_vector.shape,)
print("\n Dimension of array:", col_vector.ndim)

#Demonsterating np.expand_dims
a = np.array([1, 2, 3, 4, 5, 6])
print("\n", a, a.shape)
print("\n Dimension of array:", a.ndim)

b = np.expand_dims(a, axis=1)
print("\n", b, b.shape)
print("\n Dimension of array:", b.ndim)

c = np.expand_dims(a, axis=0)
print("\n", c, c.shape)
print("\n Dimension of array:", c.ndim)


[1 2 3 4 5 6] (6,)

 Dimension of array: 1

 [[1 2 3 4 5 6]] (1, 6)

 Dimension of array: 2

 [[1 2 3 4 5 6]] (1, 6)

 Dimension of array: 2

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)

 Dimension of array: 2

 [1 2 3 4 5 6] (6,)

 Dimension of array: 1

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)

 Dimension of array: 2

 [[1 2 3 4 5 6]] (1, 6)

 Dimension of array: 2


Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [ ]:
#creating array
n1 = np.array([56, 23])
n2 = np.array([12, 78])
print("Arrays:", n1, n2)

print("\nArray in vstack:", np.vstack((n1, n2)))

print("\nArray in hstack:", np.hstack((n1, n2)))

Arrays: [56 23] [12 78]

Array in vstack: [[56 23]
 [12 78]]

Array in hstack: [56 23 12 78]


Questions 6:
How to get unique items and counts of unique items?

In [14]:
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
      
# driver code 
list1 = [10, 20, 10, 30, 40, 40] 
print("The unique values from 1st list is") 
unique(list1) 
  
# converting our list to set 
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))

The unique values from 1st list is
[10 20 30 40]
No of unique items in the list are: 4
